
title: Shrutha Sivakumar
url: 'http://shruthasivakumar.com'
baseurl: '' #change it according to your repository name



# Profile information
yourname: Shrutha Sivakumar  ## put your name
title: 'POLICY ANALYST &amp PUBLIC HEALTH ENTHUSIAST '  ## your title
location: Berlin, Germany


## Social Profiles
# facebook: http://www.facebook.com  ## your facebook account url
# twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url

## Locations
maps:
  google:
    api_key: AIzaSyDmAgKKYHBj96FuvhiX9-lTK7XiXtyTbko

# Update all the sections by editing the files inside _includes folder.
gems:
  - jekyll-maps
